name: particular
description: "The Particular is a high performance particle effects flutter widget."
version: 0.2.5
homepage: https://manjav.github.io/particular/editor/web
repository: https://github.com/manjav/particular
issue_tracker: https://github.com/manjav/particular/issues
documentation: https://github.com/manjav/particular

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

screenshots:
  - description: 'Particular Logo'
    path: repo_files/logo.png

topics:
  - particle
  - particles
  - visualization
  - game
  - effects