name: editor
description: "Demonstrates how to use the particular package."
publish_to: 'none'

version: 0.1.0+100

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  archive: ^3.6.1
  file_picker: ^8.0.6
  flutter_colorpicker: ^1.1.0
  intry: ^0.3.2
  particular:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/